import { jsx as _jsx, jsxs as _jsxs, Fragment as _Fragment } from "react/jsx-runtime";
const formatSize = (size) => {
    if (size < 1024)
        return `${size} B`;
    if (size < 1024 * 1024)
        return `${(size / 1024).toFixed(1)} KB`;
    return `${(size / (1024 * 1024)).toFixed(1)} MB`;
};
export function FileBrowserSection({ browserData, selectedFile, browserError, isBrowsing, isLoadingFile, onRefresh, onOpenDirectory, onOpenParent, onOpenFile, }) {
    return (_jsxs("section", { className: "card", children: [_jsxs("div", { className: "file-browser-header", children: [_jsxs("div", { children: [_jsx("h2", { children: "\u30EF\u30FC\u30AF\u30B9\u30DA\u30FC\u30B9\u30D5\u30A1\u30A4\u30EB" }), _jsx("p", { className: "mono file-browser-path", children: browserData ? `cwd: /${browserData.currentPath || ""}` : "cwd: /" })] }), _jsxs("div", { className: "row", children: [_jsx("button", { onClick: onOpenParent, disabled: !browserData || browserData.parentPath === null || isBrowsing, children: "\u4E0A\u3078" }), _jsx("button", { onClick: onRefresh, disabled: isBrowsing, children: isBrowsing ? "更新中..." : "更新" })] })] }), browserData && (_jsxs("p", { className: "mono file-browser-root", children: ["Root: ", browserData.rootPath] })), browserError && _jsx("p", { className: "file-browser-error", children: browserError }), _jsxs("div", { className: "file-browser-layout", children: [_jsxs("div", { className: "file-browser-pane", children: [_jsxs("div", { className: "file-browser-pane-header", children: [_jsx("strong", { children: "\u4E00\u89A7" }), _jsxs("span", { className: "mono", children: [browserData?.entries.length ?? 0, " entries"] })] }), _jsx("div", { className: "file-browser-list", children: !browserData ? (_jsx("p", { className: "mono file-browser-empty", children: "\u307E\u3060\u8AAD\u307F\u8FBC\u3093\u3067\u3044\u307E\u305B\u3093\u3002" })) : browserData.entries.length === 0 ? (_jsx("p", { className: "mono file-browser-empty", children: "\u3053\u306E\u30C7\u30A3\u30EC\u30AF\u30C8\u30EA\u306F\u7A7A\u3067\u3059\u3002" })) : (browserData.entries.map((entry) => {
                                    const isDirectory = entry.type === "directory";
                                    return (_jsxs("button", { className: `file-browser-entry ${isDirectory ? "is-directory" : "is-file"} ${selectedFile?.path === entry.path ? "is-selected" : ""}`, onClick: () => (isDirectory ? onOpenDirectory(entry.path) : onOpenFile(entry.path)), children: [_jsxs("span", { className: "mono file-browser-entry-name", children: [isDirectory ? "[dir]" : "[file]", " ", entry.name] }), _jsx("span", { className: "mono file-browser-entry-meta", children: isDirectory ? "dir" : formatSize(entry.size) })] }, entry.path));
                                })) })] }), _jsxs("div", { className: "file-browser-pane", children: [_jsxs("div", { className: "file-browser-pane-header", children: [_jsx("strong", { children: "\u30D7\u30EC\u30D3\u30E5\u30FC" }), _jsx("span", { className: "mono", children: isLoadingFile ? "loading..." : selectedFile ? selectedFile.path : "no file" })] }), !selectedFile ? (_jsx("p", { className: "mono file-browser-empty", children: "\u30D5\u30A1\u30A4\u30EB\u3092\u9078\u3076\u3068\u5185\u5BB9\u3092\u8868\u793A\u3057\u307E\u3059\u3002" })) : (_jsxs(_Fragment, { children: [_jsxs("div", { className: "file-browser-preview-meta mono", children: [_jsx("span", { children: formatSize(selectedFile.size) }), _jsx("span", { children: new Date(selectedFile.modifiedAt).toLocaleString() }), selectedFile.truncated && _jsx("span", { children: "preview truncated" })] }), _jsx("pre", { className: "mono file-browser-preview", children: selectedFile.content })] }))] })] })] }));
}
